title: Chao PAN
email: chao.pan@eleves.enpc.fr
description: >- # this means to ignore newlines until "baseurl:"
  If you find some errors, thanks for telling me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: ""#jekyllrb
github_username:  chaopan95

# Build settings
theme: minima
plugins:
  - jekyll-feed

#for all pages
permalink: pretty

#for posts
defaults:
  - scope:
     path: ""
     type: "posts"
    values:
#this looks prettier
     permalink: /blog/:title

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

markdown: kramdown

collections:
    projects:
        output: true
    datas:
        output: true
    probs:
        output: true
    courses:
        output: true
    mls:
        output: true
    algos:
        output: true
